name: CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-docker-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image for API
        run: docker build -t flight-delay-api:latest -f Dockerfile .

      - name: Build Docker image for Airflow
        run: docker build -t flight-delay-airflow:latest -f airflow/Dockerfile airflow/


      - name: Save Docker image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: api-docker-image
          path: flight-delay-api.tar

